# Uses obi for only one purpose: rsync repo contents to a special location
# on target machines:
#
#         /data1/dev/{{project_name}}/
#
name: '{{project_name}}'
rsync-excludes: [".git", "fetched.*"]
target: "/dev/null"
build-cmd: "true"
stop-cmd: "true"
launch-cmd: "true"
rooms:
  hex:
    project-dir: "/data1/dev/{{project_name}}/"
    user: oblong
    hosts: [10.137.124.203, 10.137.124.204, 10.137.124.205, 10.137.124.206, 10.137.124.207]
  wall:
    project-dir: "/data1/dev/{{project_name}}/"
    user: oblong
    hosts: [10.137.124.200, 10.137.124.201, 10.137.124.202]
